#!/usr/bin/env bash
#
# sync.sh vendors the standard library's own flag package test suite
# (src/flag/flag_test.go) so it can be run against pflag v2 as a drop-in
# compatibility ("conformance") check. See ../README.md for the why.
#
# A separate copy is vendored per Go minor version, each guarded by a build
# constraint (e.g. `go1.26 && !go1.27`) so the toolchain running the tests
# builds exactly the copy matching its version. That makes upstream API or
# behavioral changes between Go releases show up as diffs in this directory and
# as separate pass/fail signals in the CI matrix.
#
# Usage:
#   ./sync.sh                 # re-sync every already-vendored version
#   ./sync.sh 1.25 1.26       # add/refresh copies for the named minor versions
#
# This script only adds or refreshes; it never deletes. To drop a version,
# remove its vendored file:
#   rm flag_go1.25_test.go
#
# For a requested version that matches the local toolchain, the local GOROOT
# source is used. Otherwise the file is fetched from the corresponding Go
# release branch on GitHub (requires network access).
#
# The only edits applied to the upstream file are mechanical and unavoidable:
#   - package clause:        package flag_test -> package conformance
#   - package under test:    . "flag"          -> . "github.com/spf13/pflag/v2"  (kept a dot import)
#   - internal/testenv:      -> the local shim (not importable outside the Go tree)
#   - prepend build tags + a generated banner
#
# Helpers the stdlib keeps in its internal export_test.go (DefaultUsage,
# ResetForTesting) are reimplemented against v2's public API in ../harness_test.go.

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out_dir="$(dirname "$script_dir")" # the conformance/ directory

# local toolchain minor version, e.g. "1.26" from "go1.26.4-X:nodwarf5"
local_goversion="$(go env GOVERSION)"
local_minor="$(printf '%s' "$local_goversion" | grep -oE 'go1\.[0-9]+' | head -1 | sed 's/^go//')"

# Determine which versions to vendor. With explicit args, vendor exactly those
# (use this to add or drop a version). With no args, re-sync every version
# already vendored here (discovered from the flag_go*_test.go filenames) so
# `go generate` refreshes the whole set; fall back to the local toolchain
# version when nothing is vendored yet.
if [[ $# -gt 0 ]]; then
	versions=("$@")
else
	versions=()
	for f in "$out_dir"/flag_go*_test.go; do
		[[ -e "$f" ]] || continue
		v="$(basename "$f")"
		v="${v#flag_go}"
		v="${v%_test.go}"
		versions+=("$v")
	done
	if [[ ${#versions[@]} -eq 0 ]]; then
		versions=("$local_minor")
	fi
fi

fetch_source() { # $1=minor (e.g. 1.25) -> prints flag_test.go to stdout
	local minor="$1"
	if [[ "$minor" == "$local_minor" ]]; then
		cat "$(go env GOROOT)/src/flag/flag_test.go"
	else
		local url="https://raw.githubusercontent.com/golang/go/release-branch.go${minor}/src/flag/flag_test.go"
		echo "  fetching $url" >&2
		curl -fsSL --max-time 30 "$url"
	fi
}

for minor in "${versions[@]}"; do
	major="${minor%%.*}"     # 1
	min="${minor##*.}"       # 26
	next="${major}.$((min + 1))" # 1.27
	tag="conformance && go${minor} && !go${next}"

	test_file="$out_dir/flag_go${minor}_test.go"

	echo "vendoring go${minor} -> $(basename "$test_file")"

	{
		cat <<EOF
//go:build ${tag}

// Code generated by conformance/hack/sync.sh from the Go standard library's
// flag package test suite (src/flag/flag_test.go) at go${minor}. DO NOT EDIT.
//
// This is upstream flag_test.go run against pflag v2 (dot-imported as "flag") to
// verify the drop-in-replacement promise. The build constraint pins it to the
// go${minor} toolchain so the CI matrix tests each supported Go release against
// that release's own flag tests. The only changes from upstream are the package
// clause, the dot-import target, the internal/testenv import, and a generated
// init() (just below the imports) that registers this copy with the guard in
// harness_test.go. Refresh with conformance/hack/sync.sh.

EOF
		# Apply the mechanical rewrites, then inject the version-registration
		# init() immediately after the import block (the earliest a declaration
		# is allowed — imports must precede all other top-level declarations).
		fetch_source "$minor" | sed \
			-e 's|^package flag_test$|package conformance_test|' \
			-e 's|^\(\s*\)\. "flag"$|\1. "github.com/spf13/pflag/v2"|' \
			-e 's|^\(\s*\)"internal/testenv"$|\1"github.com/spf13/pflag/v2/conformance/internal/testenv"|' |
			awk -v ver="go${minor}" '
				{ print }
				/^import \($/ { in_import = 1 }
				in_import && /^\)$/ {
					in_import = 0
					print ""
					print "// Register this vendored copy with the guard in harness_test.go so an"
					print "// un-synced Go toolchain fails loudly instead of silently testing nothing."
					print "func init() { vendoredVersion = \"" ver "\" }"
				}
			'
	} >"$test_file"

	gofmt -w "$test_file"
done

echo
echo "done. vendored: ${versions[*]}"
echo "run with: go test -tags conformance ./conformance/..."
echo "note: expected to fail until v2 implements the flag API (see conformance/README.md)."
