linters-settings:
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  dupl:
    threshold: 200
  goconst:
    min-len: 3
    min-occurrences: 2
  #forbidigo:
  #  forbid:
  #    - ^print.*$
  #    - 'fmt\.Print.*'
  gocognit:
    min-complexity: 61 # This is a rather high value. We should gradually lower it to 30-40.

linters:
  enable:
    - gofmt
    - goimports
    - bodyclose
    - dupl
    - gocognit
    - gocritic
    - goimports
    - gosec
    - nakedret
     #- nolintlint
    - revive
    - stylecheck
    - unconvert
    - unparam
  disable:
    - forbidigo
    - maligned
    - lll
    - gochecknoinits
    - gochecknoglobals
