sudo: false

language: go
arch:
  - amd64
  - ppc64le
go:
  - 1.13
  - 1.14
  - 1.15
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get golang.org/x/lint/golint
  - export PATH=$GOPATH/bin:$PATH
  - go install ./...

script:
  - verify/all.sh -v
  - go test ./...
